exporter:
  port: 9108
  # Time interval (sec) between actualization of request result
  refresh: 60
  # Possible values are info, warning, debug.
  loglevel: info

requests:
  # At this level, each occurences below "requests" will instanciate a elasticsearch.Elasticsearch() object  
  # Arbitrary value to identify each instances :
  - my_awesome_request:
      server: "my.es-server.domain.com:9200"
      # The action value will actually call a method provided by the instance.
      # it will call method by this way : Elasticsearch.<action>(**<args>)
      action: count
      args: 
        index: "<logstash-{now/d{yyyy.MM.dd}}>"
        body:
          {
            "query": {
              "bool": {
                "must": [
                    {"match": {"foo": "bar"}}
                  ]
              }
            }
          }

  - my_other_awesome_request:
  	  # If you're working on a cluster you can do this :
      server: 
        - "my.es-server-1.domain.com:9200"
        - "my.es-server-2.domain.com:9200"
        - "my.es-server-3.domain.com:9200"
      action: count
      args:
        index: "<logstash-{now/d{yyyy.MM.dd}}>"
        body:
          {
            "query": {
              "bool": {
                "must": [
                    {"match": {"foo": "bar"}}
                  ]
              }
            }
          }

metrics:
  - my_marvelous_metric:
      # Description of the metric
      description: "awesome requests here"
      # Sources are the request created above
      sources:
      - my_awesome_request:
          # On a _count request, there is a root key in the response containing the result: 
          export: count
          # You can labelize the metric by setting arbitrary key value
          labels:
            spam: egg
            foo: bar
      - my_other_awesome_request:
      	  # You can also access to element to export by specifying path like this
          export: foo.1.bar.element.value
      # !!! IMPORTANT !!! : In the same metric, you have to make sure all label keys are the same name in each time series.
      # Otherwise, the exporter will trig an exception.
          labels:
            spam: hey
            foo: peepoodo

